name: test

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
    
    - name: test
      run: |
        ls
