name: Build Nokia 4.4 KSU

on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
    
    - name: test
      run: |
        ls
